package codes

const (
	TEAM_EXISTS    = "TEAM_EXISTS"
	PR_EXISTS      = "PR_EXISTS"
	PR_MERGED      = "PR_MERGED"
	NOT_ASSIGNED   = "NOT_ASSIGNED"
	NO_CANDIDATE   = "NO_CANDIDATE"
	NOT_FOUND      = "NOT_FOUND"
	INTERNAL_ERROR = "INTERNAL_ERROR"
	INVALID_JSON   = "INVALID_JSON"
)
