// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/pull_request/pull_request.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "service-order-avito/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// CreateWithReviewers mocks base method.
func (m *MockPullRequestRepository) CreateWithReviewers(arg0 context.Context, arg1 domain.PullRequest) (*domain.PullRequestWithReviewers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithReviewers", arg0, arg1)
	ret0, _ := ret[0].(*domain.PullRequestWithReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithReviewers indicates an expected call of CreateWithReviewers.
func (mr *MockPullRequestRepositoryMockRecorder) CreateWithReviewers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithReviewers", reflect.TypeOf((*MockPullRequestRepository)(nil).CreateWithReviewers), arg0, arg1)
}

// Merge mocks base method.
func (m *MockPullRequestRepository) Merge(arg0 context.Context, arg1 string) (*domain.PullRequestWithReviewers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", arg0, arg1)
	ret0, _ := ret[0].(*domain.PullRequestWithReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge.
func (mr *MockPullRequestRepositoryMockRecorder) Merge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestRepository)(nil).Merge), arg0, arg1)
}

// ReassignReviewer mocks base method.
func (m *MockPullRequestRepository) ReassignReviewer(arg0 context.Context, arg1, arg2 string) (*domain.Reviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Reviewer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) ReassignReviewer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).ReassignReviewer), arg0, arg1, arg2)
}
