// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/server/handlers/team/team.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "service-order-avito/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamService is a mock of TeamService interface.
type MockTeamService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamServiceMockRecorder
}

// MockTeamServiceMockRecorder is the mock recorder for MockTeamService.
type MockTeamServiceMockRecorder struct {
	mock *MockTeamService
}

// NewMockTeamService creates a new mock instance.
func NewMockTeamService(ctrl *gomock.Controller) *MockTeamService {
	mock := &MockTeamService{ctrl: ctrl}
	mock.recorder = &MockTeamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamService) EXPECT() *MockTeamServiceMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *MockTeamService) AddTeam(arg0 context.Context, arg1 *dto.TeamAddRequest) (*dto.AddTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", arg0, arg1)
	ret0, _ := ret[0].(*dto.AddTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockTeamServiceMockRecorder) AddTeam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockTeamService)(nil).AddTeam), arg0, arg1)
}

// GetTeam mocks base method.
func (m *MockTeamService) GetTeam(arg0 context.Context, arg1 *dto.GetTeamRequest) (*dto.GetTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamServiceMockRecorder) GetTeam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamService)(nil).GetTeam), arg0, arg1)
}

// GetTeamStats mocks base method.
func (m *MockTeamService) GetTeamStats(arg0 context.Context, arg1 *dto.GetTeamStatsRequest) (*dto.TeamStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStats", arg0, arg1)
	ret0, _ := ret[0].(*dto.TeamStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStats indicates an expected call of GetTeamStats.
func (mr *MockTeamServiceMockRecorder) GetTeamStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStats", reflect.TypeOf((*MockTeamService)(nil).GetTeamStats), arg0, arg1)
}
