// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/server/handlers/pull_request/pull_request.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "service-order-avito/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestService is a mock of PullRequestService interface.
type MockPullRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestServiceMockRecorder
}

// MockPullRequestServiceMockRecorder is the mock recorder for MockPullRequestService.
type MockPullRequestServiceMockRecorder struct {
	mock *MockPullRequestService
}

// NewMockPullRequestService creates a new mock instance.
func NewMockPullRequestService(ctrl *gomock.Controller) *MockPullRequestService {
	mock := &MockPullRequestService{ctrl: ctrl}
	mock.recorder = &MockPullRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestService) EXPECT() *MockPullRequestServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestService) Create(arg0 context.Context, arg1 *dto.PullRequestCreateRequest) (*dto.PullRequestCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*dto.PullRequestCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestService)(nil).Create), arg0, arg1)
}

// Merge mocks base method.
func (m *MockPullRequestService) Merge(arg0 context.Context, arg1 *dto.PullRequestMergeRequest) (*dto.PullRequestMergeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", arg0, arg1)
	ret0, _ := ret[0].(*dto.PullRequestMergeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge.
func (mr *MockPullRequestServiceMockRecorder) Merge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestService)(nil).Merge), arg0, arg1)
}

// ReassignReviewer mocks base method.
func (m *MockPullRequestService) ReassignReviewer(arg0 context.Context, arg1 *dto.PullRequestReassignRequest) (*dto.PullRequestReassignResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", arg0, arg1)
	ret0, _ := ret[0].(*dto.PullRequestReassignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPullRequestServiceMockRecorder) ReassignReviewer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPullRequestService)(nil).ReassignReviewer), arg0, arg1)
}
