// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/server/handlers/user/user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "service-order-avito/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetReviewPullRequests mocks base method.
func (m *MockUserService) GetReviewPullRequests(arg0 context.Context, arg1 *dto.GetReviewPRRequest) (*dto.GetReviewPRResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewPullRequests", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetReviewPRResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewPullRequests indicates an expected call of GetReviewPullRequests.
func (mr *MockUserServiceMockRecorder) GetReviewPullRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewPullRequests", reflect.TypeOf((*MockUserService)(nil).GetReviewPullRequests), arg0, arg1)
}

// SetIsActive mocks base method.
func (m *MockUserService) SetIsActive(ctx context.Context, req *dto.SetIsActiveRequest) (*dto.SetIsActiveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, req)
	ret0, _ := ret[0].(*dto.SetIsActiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserServiceMockRecorder) SetIsActive(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserService)(nil).SetIsActive), ctx, req)
}
