// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/team/team.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "service-order-avito/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// AddTeamWithMembers mocks base method.
func (m *MockTeamRepository) AddTeamWithMembers(arg0 context.Context, arg1 domain.Team, arg2 []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeamWithMembers", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeamWithMembers indicates an expected call of AddTeamWithMembers.
func (mr *MockTeamRepositoryMockRecorder) AddTeamWithMembers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeamWithMembers", reflect.TypeOf((*MockTeamRepository)(nil).AddTeamWithMembers), arg0, arg1, arg2)
}

// GetTeamWithMembers mocks base method.
func (m *MockTeamRepository) GetTeamWithMembers(arg0 context.Context, arg1 string) (*domain.TeamWithUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWithMembers", arg0, arg1)
	ret0, _ := ret[0].(*domain.TeamWithUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWithMembers indicates an expected call of GetTeamWithMembers.
func (mr *MockTeamRepositoryMockRecorder) GetTeamWithMembers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWithMembers", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamWithMembers), arg0, arg1)
}
